url: https://nkapu.github.io
baseurl: /webkapu/

# Site settings
title: The Scandinavian ABC company
email: adm@scanabc.com
description: "Scanabc website"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/scanabc
  - title: github
    url: http://github.com/scanabc
  - title: reddit
    url: https://www.reddit.com/r/scanabc/


# Postal address (add as many lines as necessary)
address:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
